### ISSUE TITLE
[Q] send bluescreens to monolog

### ISSUE THREAD

**Issue by B0bbyD0llar** [nextras/tracy-monolog-adapter#7]
Hi,
sorry, but i don't get it. 
Simple logging works well, but how can i send bluescreen-logs to monolog instead of writing in a file.

**Comment by JanTvrdik** [comment]
I don't understand what you want. What do you mean by *sending bluescreen-logs to monolog*?

Maybe one of these will help

* [Tracy\Bridges\Psr\PsrToTracyLoggerAdapter](https://github.com/nette/tracy/blob/master/src/Bridges/Psr/PsrToTracyLoggerAdapter.php)
* [Tracy\Bridges\Psr\TracyToPsrLoggerAdapter](https://github.com/nette/tracy/blob/master/src/Bridges/Psr/TracyToPsrLoggerAdapter.php)
* [mangoweb/monolog-tracy-handler](https://github.com/mangoweb-backend/monolog-tracy-handler)

**Comment by B0bbyD0llar** [comment]
if an exception occurs, tracy shows a bluescreen, stores the bluescreen as a html-file in log folder. Additionally, it writes a message to exeception.log in configured log folder.
I want this log message send to monolog (and all connected handlers) instead to file.

Maybe the TracyExceptionProcessor is the key, but i don't get it.

**Comment by B0bbyD0llar** [comment]
> * mangoweb/monolog-tracy-handler

Unfortunately, I can't get that to work because I don't use either framework.

**Comment by JanTvrdik** [comment]
> I want this log message send to monolog (and all connected handlers) instead to file.

This requires no additional library. Simply call

```php
Tracy\Debugger::setLogger(new Tracy\Bridges\Psr\PsrToTracyLoggerAdapter($monolog));
```

**Comment by B0bbyD0llar** [comment]
Thank you very much. That was very helpful. 

Unfortunately, the html files are of course no longer saved. They did improve troubleshooting a lot though. Is there a way to have both?

Thanks for the help, although it has nothing to do with your adapter. In what use case would I want to use your adapter?

**Comment by JanTvrdik** [comment]
> Is there a way to have both?

Yes, there is. That is in fact, what this adapter is for.

~~~php
$monolog->pushProcessor(new Nextras\TracyMonologAdapter\Processors\TracyExceptionProcessor(
    __DIR__ . '/logs',
    Tracy\Debugger::getBlueScreen(),
));

Tracy\Debugger::setLogger(new Tracy\Bridges\Psr\PsrToTracyLoggerAdapter($monolog));
~~~

**Comment by B0bbyD0llar** [comment]
This works quite excellently.
Thank you very much!
